language: java

cache:
  directories:
    - ~/.m2/repository

git:
  depth: false

## export GPG details
before_install:
  - echo TRAVIS_BRANCH=$TRAVIS_BRANCH
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
  - mvn clean -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -q -DforceStdout && echo "CLEAN DONE"
  - mvn --settings default.xml package -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
  - if [[ $TRAVIS_BRANCH == "master" && $SONAR_ENABLED == "true" ]]; then mvn sonar:sonar "-Dsonar.branch.name=${TRAVIS_BRANCH}" "-Dsonar.host.url=${SONAR_URL}" "-Dsonar.login=${SONAR_TOKEN}" "-Dsonar.organization=${SONAR_ORGANISATION}"; fi
  - if [[ $TRAVIS_BRANCH != "master" && $SONAR_ENABLED == "true" ]]; then mvn sonar:sonar "-Dsonar.branch.name=${TRAVIS_BRANCH}" "-Dsonar.branch.target=master" "-Dsonar.host.url=${SONAR_URL}" "-Dsonar.login=${SONAR_TOKEN}" "-Dsonar.organization=${SONAR_ORGANISATION}"; fi

install:
  - mvn --settings default.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
  - mvn cobertura:cobertura && bash <(curl -s https://codecov.io/bash)

## Build and release to maven central
script:
  - if [[ $TRAVIS_BRANCH == "master" ]]; then mvn clean deploy --settings default.xml -DskipTests=true -B -U -Prelease; fi

## Get the project version
before_deploy:
  - export CURRENT_VERSION=$(mvn help:evaluate -q -DforceStdout -Dexpression=project.version)
  - echo CURRENT_VERSION=$CURRENT_VERSION
  - export TRAVIS_TAG=$CURRENT_VERSION
  - if [[ $TRAVIS_BRANCH != "master" ]]; then git tag $TRAVIS_TAG; fi

## Create release in GitHub
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - aemdesign-aem-core-deploy/target/aemdesign-aem-core-deploy-$CURRENT_VERSION.zip
    - aemdesign-aem-services/target/aemdesign-aem-services-$CURRENT_VERSION.jar
  skip_cleanup: true
  on:
    branch: master
  name: $CURRENT_VERSION


#notifications:
#  email: false
#  slack:
#    secure: $SLACK_TOKEN
