language: java

cache:
  directories:
    - ~/.m2/repository

git:
  depth: false

## export GPG details
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

#package:
#  mvn --settings default.xml package -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

install:
  mvn --settings default.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

## Build and release to maven central
script:
  mvn clean deploy --settings default.xml -DskipTests=true -B -U -Prelease

## Get the project version
before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')

## Create release in GitHub
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - aemdesign-aem-core-deploy/target/aemdesign-aem-core-deploy-$project_version.zip
    - aemdesign-aem-services/target/aemdesign-aem-services-$project_version.jar
  skip_cleanup: true
  name: $project_version


#notifications:
#  email: false
#  slack:
#    secure: $SLACK_TOKEN