language: java
sudo: false
cache:
  directories:
    - '$HOME/.m2/repository'

git:
  depth: false

## export GPG details
before_install:
  - echo TRAVIS_BRANCH=$TRAVIS_BRANCH
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
  - mvn clean -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -Dmaven.source.skip=true -B -q && echo "CLEAN DONE"
  - mvn package -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -Dmaven.source.skip=true -B -q && echo "PACKAGE AND LOCAL INSTALL DONE"
  - if [[ $TRAVIS_BRANCH == "master" && $SONAR_ENABLED == "true" && $TRAVIS_PULL_REQUEST == "false" ]]; then mvn sonar:sonar -q "-Dsonar.branch.name=${TRAVIS_BRANCH}" "-Dsonar.host.url=${SONAR_URL}" "-Dsonar.login=${SONAR_TOKEN}" "-Dsonar.organization=${SONAR_ORGANISATION}" && echo "SONAR ON ${TRAVIS_BRANCH} DONE"; fi
  - if [[ $TRAVIS_BRANCH != "master" && $SONAR_ENABLED == "true" ]]; then mvn sonar:sonar -q "-Dsonar.branch.name=${TRAVIS_BRANCH}" "-Dsonar.branch.target=master" "-Dsonar.host.url=${SONAR_URL}" "-Dsonar.login=${SONAR_TOKEN}" "-Dsonar.organization=${SONAR_ORGANISATION}" && echo "SONAR ON ${TRAVIS_BRANCH} DONE"; fi
  - export GIT_RELEASE_NOTES="$(git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"%h - %s (%an)")"
  - echo "READY"
  - declare -a REPO_SLUG_ARRAY="(${TRAVIS_REPO_SLUG/\// })"

install:
#  - mvn install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -q && echo "INSTALL DONE"
  - mvn test -q && bash <(curl -s https://codecov.io/bash)
  - echo "CODECOVERAGE DONE"

## Build and release to maven central
script:
  - if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]]; then mvn clean deploy --settings default.xml -B -Prelease; fi

## Get the project version, only tag if tag does not exist
before_deploy:
  - export CURRENT_VERSION=$(mvn help:evaluate -q -DforceStdout -Dexpression=project.version)
  - echo CURRENT_VERSION=$CURRENT_VERSION
  - export TRAVIS_TAG=$CURRENT_VERSION
  - if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]] && [[ -z $(git tag -l "$CURRENT_VERSION") ]]; then git tag $TRAVIS_TAG; fi

## Create release in GitHub
deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file:
      - aemdesign-aem-core-deploy/target/aemdesign-aem-core-deploy-$CURRENT_VERSION.zip
      - aemdesign-aem-services/target/aemdesign-aem-services-$CURRENT_VERSION.jar
      - aemdesign-aem-author/target/aemdesign-aem-author-$CURRENT_VERSION.zip
      - aemdesign-aem-common/target/aemdesign-aem-common-$CURRENT_VERSION.zip
    skip_cleanup: true
    tag_name: $CURRENT_VERSION
    name: $CURRENT_VERSION
    target_commitish: $TRAVIS_COMMIT
    body: $GIT_RELEASE_NOTES
    on:
      branch: master
  - provider: script
    script: if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]]; then bash docker run --rm aemdesign/travis-trigger-build sbb --github_user=${REPO_SLUG_ARRAY[0]} --github_repo=aem --github_branch=6.5.0-bundle --travis_token=${TRAVIS_TOKEN}; fi
  - provider: script
    script: if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]]; then bash docker run --rm aemdesign/travis-trigger-build sbb --github_user=${REPO_SLUG_ARRAY[0]} --github_repo=aem --github_branch=6.4.0-bundle --travis_token=${TRAVIS_TOKEN}; fi

#notifications:
#  email: false
#  slack:
#    secure: $SLACK_TOKEN
