#!/bin/bash

function set_term_title() {
   echo -en "\033]0;$1\a"
}

set_term_title "Deploying Project: mvn -Dvault.useProxy=false -DskipTests clean install -P autoInstallBundle,autoInstallPackage"
#mvn -DskipTests clean install -P autoCleanInstallPackage
#mvn -Dvault.useProxy=false -DskipTests clean install -P autoInstallBundle,autoInstallPackage,autoInstallPackagePublish
mvn -Dvault.useProxy=false -DskipTests clean install -P autoInstallPackage -Dcrx.host=localhost
set_term_title "Deployed"

