#!/bin/bash

function set_term_title() {
   echo -en "\033]0;$1\a"
}

set_term_title "Deploying Project"
#mvn -DskipTests clean install -P autoCleanInstallPackage
#mvn -Dvault.useProxy=false -DskipTests clean install -P autoInstallBundle,autoInstallPackage,autoInstallPackagePublish
#mvn -Dvault.useProxy=false -DskipTests clean install -P autoInstallBundle,autoInstallPackage
mvn \
    -Pjava7 \
    -Dmaven.compiler.source=1.7 \
    -Dmaven.compiler.target=1.7 \
    -Dvault.useProxy=false \
    -DskipTests \
    deploy \
    -P autoInstallBundle \
    -Dmaven.deploy.skip=true \
    -DskipNexusStagingDeployMojo=true \
    -Dcrx.host=localhost

set_term_title "Deployed"


