#!/bin/bash

PARENT_PROJECT_PATH="$(realpath ..)"
SCRIPT_PARAMS="$@"

source "../scripts/functions.sh"

set_term_title "Common Deploy"
echo "- Deploy"
mvn -Dvault.useProxy=false -DskipTests clean install -P autoInstallPackage "$@"
echo "- Deployed"

