#!/bin/bash

POM_FILE="../pom.xml"
PARENT_PROJECT_PATH="$(realpath ..)"
SCRIPT_PARAMS="$@"

source "../scripts/functions.sh"

set_term_title "Deploying Project"
mvn -Dvault.useProxy=false -DskipTests clean install -P installdeploymentpackage "$@"

set_term_title "Deployed"

