#!/bin/bash

function set_term_title() {
   echo -en "\033]0;$1\a"
}

set_term_title "Deploying Project"
mvn -Dvault.useProxy=false -DskipTests clean install -P installdeploymentpackage "$@"

set_term_title "Deployed"

